name: CI

on:
  push:
    branches: [main]
    tags: ['**']
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  RUST_TOOLCHAIN: '1.83.0'
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        run: |
          rustup set profile minimal
          rustup toolchain install "$RUST_TOOLCHAIN"
          rustup override set "$RUST_TOOLCHAIN"

      - uses: Swatinem/rust-cache@v2

      - run: cargo check

  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        run: |
          rustup set profile minimal
          rustup toolchain install "$RUST_TOOLCHAIN"
          rustup override set "$RUST_TOOLCHAIN"

      - uses: Swatinem/rust-cache@v2

      - name: Run cargo test
        run: cargo test -- --test-threads=1

  docs:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        run: |
          rustup set profile minimal
          rustup toolchain install "$RUST_TOOLCHAIN"
          rustup override set "$RUST_TOOLCHAIN"

      - uses: Swatinem/rust-cache@v2

      - name: Run cargo doc
        run: cargo doc --no-deps --document-private-items --all-features

  format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        run: |
          rustup set profile minimal
          rustup toolchain install "$RUST_TOOLCHAIN" --component rustfmt
          rustup override set "$RUST_TOOLCHAIN"

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        run: |
          rustup set profile minimal
          rustup toolchain install "$RUST_TOOLCHAIN" --component clippy
          rustup override set "$RUST_TOOLCHAIN"

      - uses: Swatinem/rust-cache@v2

      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [check, test, docs, format, lint]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        run: |
          rustup set profile minimal
          rustup toolchain install "$RUST_TOOLCHAIN"
          rustup override set "$RUST_TOOLCHAIN"

      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
