name: CI

on:
  push:
    branches: [main]
    tags: ['**']
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  RUST_VERSION: 1.68.2
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          profile: minimal
          override: true

      - uses: ciffelia/cargo-cache-action@v1
        with:
          hash-files: Cargo.toml

      - name: Check
        run: cargo check

  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          profile: minimal
          override: true

      - uses: ciffelia/cargo-cache-action@v1
        with:
          hash-files: Cargo.toml

      - name: Run test
        run: cargo test -- --test-threads=1

  docs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          profile: minimal
          override: true

      - uses: ciffelia/cargo-cache-action@v1
        with:
          hash-files: Cargo.toml

      - name: Generate documentation
        run: cargo doc --no-deps --document-private-items --all-features

  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          profile: minimal
          components: rustfmt
          override: true

      - name: Check code format
        run: cargo fmt --all -- --check

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          override: true
          profile: minimal
          components: clippy

      - uses: ciffelia/cargo-cache-action@v1
        with:
          hash-files: Cargo.toml

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [check, test, docs, format, lint]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          profile: minimal
          override: true

      - name: Publish package
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
